# Generated by Django 3.2.9 on 2021-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0003_productsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeneedsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
